apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.port.frontendPort }}
      protocol: TCP
      targetPort: {{ .Values.global.port.frontendPort }}
  selector:
    app: frontend
